import { useMemo, useState } from 'react'
import { abtBlueprintBlocks, abtBlueprintSummary } from '../data/abtBlueprint'
import type { ABTBlueprintBlock } from '../types/abtBlueprint'
import { BadgeList } from '../components/ui/BadgeList'
import { KnowledgeChain } from '../components/knowledge/KnowledgeChain'

interface Props { focusId?: string | null }
const allValue = 'All'
const statusOptions = [allValue, ...Array.from(new Set(abtBlueprintBlocks.map((x) => x.status))).sort()]
const blockOptions = [allValue, ...Array.from(new Set(abtBlueprintBlocks.map((x) => x.block))).sort()]

export function ABTBlueprintPage({ focusId }: Props) {
  const [status, setStatus] = useState(allValue)
  const [block, setBlock] = useState(allValue)
  const [query, setQuery] = useState('')
  const visible = useMemo(() => { const q = query.trim().toLowerCase(); return abtBlueprintBlocks.filter((x) => status === allValue || x.status === status).filter((x) => block === allValue || x.block === block).filter((x) => !q || [x.title,x.status,x.block,x.purpose,x.nextAction,...x.designRules,...x.inputs,...x.outputs,...x.checks,...x.risks,...x.linkedFieldGroups,...x.targetLessons].join(' ').toLowerCase().includes(q)).sort((a,b)=>(a.id===focusId?-1:b.id===focusId?1:a.block.localeCompare(b.block)||a.title.localeCompare(b.title))) }, [block, focusId, query, status])
  return <section className="page-stack">{focusId && <div className="deep-link-banner">Opened from Search · focused ABT block</div>}<div className="hero-panel abt-hero"><div><span className="eyebrow">Sprint 5.6 · ABT Design Blueprint</span><h1>Design the analytical base table before modeling credit risk.</h1><p>Blueprint for grain, windows, features, split logic and schema. It remains controlled until field refs are reviewed.</p></div><div className="abt-score-card"><span className="eyebrow">ABT Blocks</span><strong>{abtBlueprintSummary.total}</strong><p>{abtBlueprintSummary.blueprint} blueprint · {abtBlueprintSummary.pendingRefs} pending refs</p><div className="inventory-mini-stats"><span>{abtBlueprintSummary.reviewReady} review ready</span><span>schema</span></div></div></div><section className="manual-panel warning"><span className="eyebrow">Design rule</span><h2>Blueprint first, source-backed later.</h2><p>This page defines the table design. It does not finalize fields until LCDataDictionary sheet refs are checked.</p></section><section className="manual-panel result-impact"><span className="eyebrow">ABT Design Flow</span><h2>Grain → observation window → performance window → features → split → schema</h2><KnowledgeChain nodes={['Grain','Observation Window','Performance Window','Feature Groups','Split Design','ABT Schema']} /></section><section className="manual-panel inventory-filter-panel"><div className="library-filter-header"><div><span className="eyebrow">Blueprint Filters</span><h2>{visible.length} of {abtBlueprintBlocks.length} blocks visible</h2></div><button className="text-button" onClick={() => { setStatus(allValue); setBlock(allValue); setQuery('') }} type="button">Clear filters</button></div><input className="library-search-input" value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search grain, window, target, split, leakage, schema..." /><div className="library-filter-grid"><Select label="Status" value={status} values={statusOptions} onChange={setStatus} /><Select label="Block" value={block} values={blockOptions} onChange={setBlock} /></div></section><section className="abt-grid">{visible.map((x) => <Card key={x.id} item={x} focused={x.id === focusId} />)}</section></section>
}
function Card({ item, focused }: { item: ABTBlueprintBlock; focused: boolean }) { const cls = item.status.toLowerCase().split(' ').join('-'); return <article className={`abt-card ${focused ? 'focused-result-card' : ''}`}><div className="abt-card-top"><span className="eyebrow">{item.block}</span><span className={`abt-pill ${cls}`}>{item.status}</span></div><h3>{item.title}</h3><p>{item.purpose}</p><h4>Design rules</h4><ul>{item.designRules.map((x)=><li key={x}>{x}</li>)}</ul><h4>Inputs</h4><BadgeList items={item.inputs} tone="blue" /><h4>Outputs</h4><BadgeList items={item.outputs} tone="green" /><h4>Checks</h4><BadgeList items={item.checks} tone="amber" /><h4>Risks</h4><ul>{item.risks.map((x)=><li key={x}>{x}</li>)}</ul><h4>Linked field groups</h4><BadgeList items={item.linkedFieldGroups} tone="purple" /><h4>Study links</h4><BadgeList items={item.targetLessons} tone="blue" /><h4>Next action</h4><KnowledgeChain nodes={[item.nextAction]} /></article> }
function Select({ label, value, values, onChange }: { label:string; value:string; values:string[]; onChange:(v:string)=>void }) { return <label className="library-select"><span>{label}</span><select value={value} onChange={(e)=>onChange(e.target.value)}>{values.map((x)=><option key={x} value={x}>{x}</option>)}</select></label> }
