import { useMemo, useState } from 'react'
import { abtFieldReviewItems, abtFieldReviewSummary } from '../data/abtFieldReview'
import type { ABTFieldReviewItem } from '../types/abtFieldReview'
import { BadgeList } from '../components/ui/BadgeList'
import { KnowledgeChain } from '../components/knowledge/KnowledgeChain'

interface Props { focusId?: string | null }
const allValue = 'All'
const decisionOptions = [allValue, ...Array.from(new Set(abtFieldReviewItems.map((x) => x.decision))).sort()]
const riskOptions = [allValue, ...Array.from(new Set(abtFieldReviewItems.map((x) => x.risk))).sort()]
const sectionOptions = [allValue, ...Array.from(new Set(abtFieldReviewItems.map((x) => x.section))).sort()]

export function ABTFieldReviewMatrixPage({ focusId }: Props) {
  const [decision, setDecision] = useState(allValue)
  const [risk, setRisk] = useState(allValue)
  const [section, setSection] = useState(allValue)
  const [query, setQuery] = useState('')
  const visible = useMemo(() => { const q = query.trim().toLowerCase(); return abtFieldReviewItems.filter((x) => decision === allValue || x.decision === decision).filter((x) => risk === allValue || x.risk === risk).filter((x) => section === allValue || x.section === section).filter((x) => !q || [x.fieldName,x.section,x.decision,x.risk,x.reviewQuestion,x.allowedUse,x.blockedUse,x.linkedSchemaColumn,x.linkedStudyUpdate,x.nextAction,...x.evidenceNeeded,...x.qualityChecks].join(' ').toLowerCase().includes(q)).sort((a,b)=>(a.id===focusId?-1:b.id===focusId?1:a.section.localeCompare(b.section)||a.fieldName.localeCompare(b.fieldName))) }, [decision, focusId, query, risk, section])
  return <section className="page-stack">{focusId && <div className="deep-link-banner">Opened from Search · focused field review item</div>}<div className="hero-panel abt-review-hero"><div><span className="eyebrow">Sprint 5.8 · ABT Field Review Matrix</span><h1>Review each schema field before it becomes model-ready.</h1><p>Matrix for decisions, risk levels, evidence needs, quality checks, allowed use and blocked use.</p></div><div className="abt-review-score-card"><span className="eyebrow">Review Items</span><strong>{abtFieldReviewSummary.total}</strong><p>{abtFieldReviewSummary.hold} hold · {abtFieldReviewSummary.ownerReview} owner review</p><div className="inventory-mini-stats"><span>{abtFieldReviewSummary.highRisk} high risk</span><span>{abtFieldReviewSummary.accept} accept</span></div></div></div><section className="manual-panel warning"><span className="eyebrow">Review rule</span><h2>No field becomes model-ready without evidence and allowed-use review.</h2><p>This matrix separates accepted candidates, fields held for evidence, blocked uses and owner review needs.</p></section><section className="manual-panel result-impact"><span className="eyebrow">Field Review Flow</span><h2>Schema column → evidence → risk → allowed use → blocked use → decision</h2><KnowledgeChain nodes={['Schema Column','Evidence Need','Risk Level','Allowed Use','Blocked Use','Decision']} /></section><section className="manual-panel inventory-filter-panel"><div className="library-filter-header"><div><span className="eyebrow">Review Filters</span><h2>{visible.length} of {abtFieldReviewItems.length} review items visible</h2></div><button className="text-button" onClick={() => { setDecision(allValue); setRisk(allValue); setSection(allValue); setQuery('') }} type="button">Clear filters</button></div><input className="library-search-input" value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search field, target, cutoff, source ref, leakage, feature use..." /><div className="library-filter-grid"><Select label="Decision" value={decision} values={decisionOptions} onChange={setDecision} /><Select label="Risk" value={risk} values={riskOptions} onChange={setRisk} /><Select label="Section" value={section} values={sectionOptions} onChange={setSection} /></div></section><section className="abt-review-grid">{visible.map((x) => <Card key={x.id} item={x} focused={x.id === focusId} />)}</section></section>
}
function Card({ item, focused }: { item: ABTFieldReviewItem; focused: boolean }) { const cls = item.decision.toLowerCase().split(' ').join('-'); const riskCls = item.risk.toLowerCase(); return <article className={`abt-review-card ${focused ? 'focused-result-card' : ''}`}><div className="abt-review-card-top"><span className="eyebrow">{item.section} · {item.risk} risk</span><span className={`abt-review-pill ${cls}`}>{item.decision}</span></div><h3>{item.fieldName}</h3><span className={`abt-risk-pill ${riskCls}`}>{item.risk}</span><p>{item.reviewQuestion}</p><h4>Evidence needed</h4><BadgeList items={item.evidenceNeeded} tone="amber" /><h4>Quality checks</h4><BadgeList items={item.qualityChecks} tone="green" /><h4>Allowed use</h4><p>{item.allowedUse}</p><h4>Blocked use</h4><p>{item.blockedUse}</p><h4>Links</h4><BadgeList items={[item.linkedSchemaColumn, item.linkedStudyUpdate]} tone="purple" /><h4>Next action</h4><KnowledgeChain nodes={[item.nextAction]} /></article> }
function Select({ label, value, values, onChange }: { label:string; value:string; values:string[]; onChange:(v:string)=>void }) { return <label className="library-select"><span>{label}</span><select value={value} onChange={(e)=>onChange(e.target.value)}>{values.map((x)=><option key={x} value={x}>{x}</option>)}</select></label> }
