import { useMemo, useState } from 'react'
import { abtSchemaColumns, abtSchemaSummary } from '../data/abtSchemaTemplate'
import type { ABTSchemaColumn } from '../types/abtSchemaTemplate'
import { BadgeList } from '../components/ui/BadgeList'
import { KnowledgeChain } from '../components/knowledge/KnowledgeChain'

interface Props { focusId?: string | null }
const allValue = 'All'
const sectionOptions = [allValue, ...Array.from(new Set(abtSchemaColumns.map((x) => x.section))).sort()]
const statusOptions = [allValue, ...Array.from(new Set(abtSchemaColumns.map((x) => x.status))).sort()]

export function ABTSchemaTemplatePage({ focusId }: Props) {
  const [section, setSection] = useState(allValue)
  const [status, setStatus] = useState(allValue)
  const [query, setQuery] = useState('')
  const visible = useMemo(() => { const q = query.trim().toLowerCase(); return abtSchemaColumns.filter((x) => section === allValue || x.section === section).filter((x) => status === allValue || x.status === status).filter((x) => !q || [x.name,x.section,x.status,x.purpose,x.sourceRule,x.qualityRule,x.linkedBlueprintBlock,x.nextAction,...x.exampleValues].join(' ').toLowerCase().includes(q)).sort((a,b)=>(a.id===focusId?-1:b.id===focusId?1:a.section.localeCompare(b.section)||a.name.localeCompare(b.name))) }, [focusId, query, section, status])
  return <section className="page-stack">{focusId && <div className="deep-link-banner">Opened from Search · focused schema column</div>}<div className="hero-panel abt-schema-hero"><div><span className="eyebrow">Sprint 5.7 · ABT Schema Template</span><h1>Concrete schema template for the lending analytical base table.</h1><p>Defines keys, dates, target columns, feature groups, excluded fields, quality checks and review metadata.</p></div><div className="abt-schema-score-card"><span className="eyebrow">Schema Columns</span><strong>{abtSchemaSummary.total}</strong><p>{abtSchemaSummary.template} template · {abtSchemaSummary.pendingRefs} pending refs</p><div className="inventory-mini-stats"><span>{abtSchemaSummary.reviewRequired} review required</span><span>ABT</span></div></div></div><section className="manual-panel warning"><span className="eyebrow">Schema rule</span><h2>Template columns are not final source-backed fields.</h2><p>Columns become approved only after field source references and review status are completed.</p></section><section className="manual-panel result-impact"><span className="eyebrow">Schema Flow</span><h2>Keys → dates → target → features → exclusions → quality → review status</h2><KnowledgeChain nodes={['Keys','Dates','Target','Features','Excluded','Quality','Review']} /></section><section className="manual-panel inventory-filter-panel"><div className="library-filter-header"><div><span className="eyebrow">Schema Filters</span><h2>{visible.length} of {abtSchemaColumns.length} columns visible</h2></div><button className="text-button" onClick={() => { setSection(allValue); setStatus(allValue); setQuery('') }} type="button">Clear filters</button></div><input className="library-search-input" value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search target, feature, cutoff, excluded, quality, review..." /><div className="library-filter-grid"><Select label="Section" value={section} values={sectionOptions} onChange={setSection} /><Select label="Status" value={status} values={statusOptions} onChange={setStatus} /></div></section><section className="abt-schema-grid">{visible.map((x) => <Card key={x.id} item={x} focused={x.id === focusId} />)}</section></section>
}
function Card({ item, focused }: { item: ABTSchemaColumn; focused: boolean }) { const cls = item.status.toLowerCase().split(' ').join('-'); return <article className={`abt-schema-card ${focused ? 'focused-result-card' : ''}`}><div className="abt-schema-card-top"><span className="eyebrow">{item.section}</span><span className={`abt-schema-pill ${cls}`}>{item.status}</span></div><h3>{item.name}</h3><p>{item.purpose}</p><h4>Example values</h4><BadgeList items={item.exampleValues} tone="blue" /><h4>Source rule</h4><p>{item.sourceRule}</p><h4>Quality rule</h4><p>{item.qualityRule}</p><h4>Linked blueprint block</h4><BadgeList items={[item.linkedBlueprintBlock]} tone="purple" /><h4>Next action</h4><KnowledgeChain nodes={[item.nextAction]} /></article> }
function Select({ label, value, values, onChange }: { label:string; value:string; values:string[]; onChange:(v:string)=>void }) { return <label className="library-select"><span>{label}</span><select value={value} onChange={(e)=>onChange(e.target.value)}>{values.map((x)=><option key={x} value={x}>{x}</option>)}</select></label> }
