import { useMemo, useState } from 'react'
import { academicUpgradeItems, academicUpgradeSummary } from '../data/academicUpgradePass'
import type { AcademicUpgradeItem } from '../types/academicUpgrade'
import { BadgeList } from '../components/ui/BadgeList'
import { KnowledgeChain } from '../components/knowledge/KnowledgeChain'

interface AcademicUpgradePassPageProps { focusId?: string | null }
const allValue = 'All'
const areaOptions = [allValue, ...Array.from(new Set(academicUpgradeItems.map((item) => item.area))).sort()]
const statusOptions = [allValue, ...Array.from(new Set(academicUpgradeItems.map((item) => item.status))).sort()]

export function AcademicUpgradePassPage({ focusId }: AcademicUpgradePassPageProps) {
  const [area, setArea] = useState(allValue)
  const [status, setStatus] = useState(allValue)
  const [query, setQuery] = useState('')
  const visible = useMemo(() => { const q = query.trim().toLowerCase(); return academicUpgradeItems.filter((item) => area === allValue || item.area === area).filter((item) => status === allValue || item.status === status).filter((item) => !q || [item.title,item.area,item.status,item.sourceFile,item.driveId,item.currentLimitation,item.upgradeAction,item.sourceRule,item.nextStep,...item.targetStudyModules,...item.targetLessons,...item.targetAssets,...item.evidenceToExtract,...item.reviewQuestions].join(' ').toLowerCase().includes(q)).sort((a,b)=>(a.id===focusId?-1:b.id===focusId?1:b.confidence-a.confidence||a.title.localeCompare(b.title))) }, [area, focusId, query, status])
  return <section className="page-stack">{focusId && <div className="deep-link-banner">Opened from Global Search · focused academic upgrade item</div>}<div className="hero-panel academic-upgrade-hero"><div><span className="eyebrow">Sprint 5.0 · Academic Source Upgrade Pass</span><h1>Controlled upgrade path from real master documents into Study-first modules.</h1><p>Each item defines which file to review, what evidence to extract, which lessons to upgrade and what cannot be promoted yet.</p></div><div className="academic-upgrade-score-card"><span className="eyebrow">Upgrade Queue</span><strong>{academicUpgradeSummary.avgConfidence}%</strong><p>{academicUpgradeSummary.total} items · {academicUpgradeSummary.ready} ready to review</p><div className="inventory-mini-stats"><span>{academicUpgradeSummary.promotion} promotion</span><span>{academicUpgradeSummary.extraction} extract</span></div></div></div><section className="manual-panel result-impact"><span className="eyebrow">Upgrade Flow</span><h2>File → evidence extraction → review questions → target lessons → controlled promotion</h2><KnowledgeChain nodes={['Academic File','Evidence to Extract','Review Questions','Target Lessons','Controlled Promotion','Study Module Update']} /></section><section className="manual-panel warning"><span className="eyebrow">Source Rule</span><h2>No academic-backed claim without reviewed evidence.</h2><p>These items organize the review queue. They do not claim that the content is already academically approved.</p></section><section className="manual-panel inventory-filter-panel"><div className="library-filter-header"><div><span className="eyebrow">Upgrade Filters</span><h2>{visible.length} of {academicUpgradeItems.length} upgrade items visible</h2></div><button className="text-button" onClick={() => { setArea(allValue); setStatus(allValue); setQuery('') }} type="button">Clear filters</button></div><input className="library-search-input" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search RetailCreditScoring, KS, LCDataDictionary, graph algorithms, credit scoring best practices..." /><div className="library-filter-grid"><AcademicSelect label="Area" value={area} values={areaOptions} onChange={setArea} /><AcademicSelect label="Status" value={status} values={statusOptions} onChange={setStatus} /></div></section><section className="academic-upgrade-grid">{visible.map((item) => <AcademicUpgradeCard key={item.id} item={item} focused={item.id === focusId} />)}</section></section>
}
function AcademicUpgradeCard({ item, focused }: { item: AcademicUpgradeItem; focused: boolean }) { const statusClass = item.status.toLowerCase().split(' ').join('-'); return <article className={`academic-upgrade-card ${focused ? 'focused-result-card' : ''}`}><div className="academic-upgrade-card-top"><span className="eyebrow">{item.area}</span><span className={`academic-upgrade-pill ${statusClass}`}>{item.status}</span></div><div className="academic-upgrade-score-row"><h3>{item.title}</h3><strong>{item.confidence}%</strong></div><p><strong>File:</strong> {item.sourceFile}</p><p><strong>Drive ID:</strong> {item.driveId}</p><div className="mini-result warning"><strong>Current limitation:</strong> {item.currentLimitation}</div><h4>Target study modules</h4><BadgeList items={item.targetStudyModules} tone="blue" /><h4>Target lessons</h4><BadgeList items={item.targetLessons} tone="purple" /><h4>Target assets</h4><BadgeList items={item.targetAssets} tone="green" /><h4>Evidence to extract</h4><BadgeList items={item.evidenceToExtract} tone="amber" /><h4>Upgrade action</h4><p>{item.upgradeAction}</p><h4>Review questions</h4><ul>{item.reviewQuestions.map((x)=><li key={x}>{x}</li>)}</ul><div className="mini-result good"><strong>Source rule:</strong> {item.sourceRule}</div><h4>Next step</h4><KnowledgeChain nodes={[item.nextStep]} /></article> }
function AcademicSelect({ label, value, values, onChange }: { label: string; value: string; values: string[]; onChange: (value: string) => void }) { return <label className="library-select"><span>{label}</span><select value={value} onChange={(event) => onChange(event.target.value)}>{values.map((item)=><option key={item} value={item}>{item}</option>)}</select></label> }
