import { useMemo, useState } from 'react'
import { academicNotes, academicNoteSummary } from '../data/academicNotes'
import type { AcademicNote } from '../types/academicNote'
import { BadgeList } from '../components/ui/BadgeList'
import { KnowledgeChain } from '../components/knowledge/KnowledgeChain'

interface AcademicNotesPageProps { focusId?: string | null }
const allValue = 'All'
const domainOptions = [allValue, ...Array.from(new Set(academicNotes.map((item) => item.domain))).sort()]
const statusOptions = [allValue, ...Array.from(new Set(academicNotes.map((item) => item.status))).sort()]
const firstPassCount = academicNoteSummary.firstPass ?? academicNotes.filter((item) => item.status === 'First pass').length

export function AcademicNotesPage({ focusId }: AcademicNotesPageProps) {
  const [domain, setDomain] = useState(allValue)
  const [status, setStatus] = useState(allValue)
  const [query, setQuery] = useState('')
  const visible = useMemo(() => { const q = query.trim().toLowerCase(); return academicNotes.filter((item) => domain === allValue || item.domain === domain).filter((item) => status === allValue || item.status === status).filter((item) => !q || [item.title,item.domain,item.status,item.file,item.fileId,item.role,item.summary,item.recommendation,item.next,...item.topics,...item.formulas,...item.models,...item.outputs,...item.cases,...item.refs,...item.updates,...item.checks].join(' ').toLowerCase().includes(q)).sort((a,b)=>(a.id===focusId?-1:b.id===focusId?1:a.domain.localeCompare(b.domain)||a.title.localeCompare(b.title))) }, [domain, focusId, query, status])
  return <section className="page-stack">{focusId && <div className="deep-link-banner">Opened from Search · focused academic note</div>}<div className="hero-panel academic-notes-hero"><div><span className="eyebrow">Sprint 5.1 · Evidence Extraction Notes</span><h1>Document-by-document extraction notes for academic upgrade.</h1><p>Each note is a controlled workspace for topics, formulas, models, outputs, cases, missing refs and proposed Study Module updates.</p></div><div className="academic-notes-score-card"><span className="eyebrow">Extraction Notes</span><strong>{academicNoteSummary.total}</strong><p>{academicNoteSummary.pending} pending · {firstPassCount} first pass</p><div className="inventory-mini-stats"><span>{academicNoteSummary.needsRefs} needs refs</span><span>{academicNoteSummary.reviewReady} review ready</span></div></div></div><section className="manual-panel warning"><span className="eyebrow">Academic honesty rule</span><h2>Notes are not approval.</h2><p>These cards organize what to extract. Page references and exact file review are still required before any source-backed promotion.</p></section><section className="manual-panel result-impact"><span className="eyebrow">Extraction Flow</span><h2>Document → topics → formulas/models/outputs/cases → refs → recommendation → Study update</h2><KnowledgeChain nodes={['Document','Topics','Formulas / Models','Outputs / Cases','Refs Needed','Promotion Recommendation','Study Updates']} /></section><section className="manual-panel inventory-filter-panel"><div className="library-filter-header"><div><span className="eyebrow">Note Filters</span><h2>{visible.length} of {academicNotes.length} notes visible</h2></div><button className="text-button" onClick={() => { setDomain(allValue); setStatus(allValue); setQuery('') }} type="button">Clear filters</button></div><input className="library-search-input" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search KS, RetailCreditScoring, LCDataDictionary, graph algorithms, formulas, outputs..." /><div className="library-filter-grid"><NoteSelect label="Domain" value={domain} values={domainOptions} onChange={setDomain} /><NoteSelect label="Status" value={status} values={statusOptions} onChange={setStatus} /></div></section><section className="academic-notes-grid">{visible.map((item) => <AcademicNoteCard key={item.id} item={item} focused={item.id === focusId} />)}</section></section>
}
function AcademicNoteCard({ item, focused }: { item: AcademicNote; focused: boolean }) { const statusClass = item.status.toLowerCase().split(' ').join('-'); return <article className={`academic-note-card ${focused ? 'focused-result-card' : ''}`}><div className="academic-note-card-top"><span className="eyebrow">{item.domain}</span><span className={`academic-note-pill ${statusClass}`}>{item.status}</span></div><h3>{item.title}</h3><p><strong>File:</strong> {item.file}</p><p><strong>File ID:</strong> {item.fileId}</p><div className="mini-result good"><strong>Document role:</strong> {item.role}</div><p>{item.summary}</p><h4>Topics to extract</h4><BadgeList items={item.topics} tone="blue" /><h4>Formulas</h4><BadgeList items={item.formulas} tone="green" /><h4>Models</h4><BadgeList items={item.models} tone="purple" /><h4>Outputs</h4><BadgeList items={item.outputs} tone="amber" /><h4>Cases</h4><BadgeList items={item.cases} tone="blue" /><h4>Refs needed</h4><BadgeList items={item.refs} tone="amber" /><div className="mini-result warning"><strong>Promotion recommendation:</strong> {item.recommendation}</div><h4>Target Study updates</h4><BadgeList items={item.updates} tone="purple" /><h4>Quality checks</h4><ul>{item.checks.map((x)=><li key={x}>{x}</li>)}</ul><h4>Next extraction step</h4><KnowledgeChain nodes={[item.next]} /></article> }
function NoteSelect({ label, value, values, onChange }: { label:string; value:string; values:string[]; onChange:(value:string)=>void }) { return <label className="library-select"><span>{label}</span><select value={value} onChange={(event)=>onChange(event.target.value)}>{values.map((item)=><option key={item} value={item}>{item}</option>)}</select></label> }
