import { useMemo, useState } from 'react'
import { capstoneProjects, capstoneSummary } from '../data/capstoneProjects'
import type { CapstoneProject } from '../types/capstoneProject'
import { BadgeList } from '../components/ui/BadgeList'
import { KnowledgeChain } from '../components/knowledge/KnowledgeChain'

interface CapstoneProjectsPageProps { focusId?: string | null }
const allValue = 'All'
const areaOptions = [allValue, ...Array.from(new Set(capstoneProjects.map((item) => item.area))).sort()]
const levelOptions = [allValue, ...Array.from(new Set(capstoneProjects.map((item) => item.level))).sort()]

export function CapstoneProjectsPage({ focusId }: CapstoneProjectsPageProps) {
  const [area, setArea] = useState(allValue)
  const [level, setLevel] = useState(allValue)
  const [query, setQuery] = useState('')
  const visible = useMemo(() => { const q = query.trim().toLowerCase(); return capstoneProjects.filter((item) => area === allValue || item.area === area).filter((item) => level === allValue || item.level === level).filter((item) => !q || [item.title,item.area,item.level,item.duration,item.professionalGoal,item.businessQuestion,...item.requiredInputs,...item.workflow,...item.formulas,...item.models,...item.outputs,...item.deliverables,...item.evaluationCriteria,...item.connectedModules,...item.practiceLinks,item.portfolioUse].join(' ').toLowerCase().includes(q)).sort((a,b)=>(a.id===focusId?-1:b.id===focusId?1:a.area.localeCompare(b.area)||a.title.localeCompare(b.title))) }, [area, focusId, level, query])
  return <section className="page-stack">{focusId && <div className="deep-link-banner">Opened from Global Search · focused capstone project</div>}<div className="hero-panel capstone-hero"><div><span className="eyebrow">Sprint 4.5 · Capstone Projects</span><h1>Final professional projects for your Knowledge Hub portfolio.</h1><p>Use capstones to combine modules, formulas, outputs, models and practice into complete analyst-style deliverables.</p></div><div className="capstone-score-card"><span className="eyebrow">Project Portfolio</span><strong>{capstoneSummary.total}</strong><p>{capstoneSummary.professional} professional-level projects</p><div className="inventory-mini-stats"><span>{capstoneSummary.outputs} outputs</span><span>{capstoneSummary.deliverables} deliverables</span></div></div></div><section className="manual-panel result-impact"><span className="eyebrow">Capstone Flow</span><h2>Question → inputs → workflow → models/formulas → outputs → portfolio deliverable</h2><KnowledgeChain nodes={['Business Question','Inputs','Workflow','Models / Formulas','Outputs','Final Deliverable','Portfolio Story']} /></section><section className="manual-panel inventory-filter-panel"><div className="library-filter-header"><div><span className="eyebrow">Project Filters</span><h2>{visible.length} of {capstoneProjects.length} projects visible</h2></div><button className="text-button" onClick={() => { setArea(allValue); setLevel(allValue); setQuery('') }} type="button">Clear filters</button></div><input className="library-search-input" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search banking, valuation, dashboard, market brief, strategy, CFA or Bloomberg..." /><div className="library-filter-grid"><CapstoneSelect label="Area" value={area} values={areaOptions} onChange={setArea} /><CapstoneSelect label="Level" value={level} values={levelOptions} onChange={setLevel} /></div></section><section className="capstone-grid">{visible.map((item) => <CapstoneCard key={item.id} item={item} focused={item.id === focusId} />)}</section></section>
}
function CapstoneCard({ item, focused }: { item: CapstoneProject; focused: boolean }) { return <article className={`capstone-card ${focused ? 'focused-result-card' : ''}`}><div className="capstone-card-top"><span className="eyebrow">{item.area} · {item.level}</span><span className="capstone-pill">{item.duration}</span></div><h3>{item.title}</h3><p>{item.professionalGoal}</p><div className="mini-result good"><strong>Business question:</strong> {item.businessQuestion}</div><h4>Required inputs</h4><BadgeList items={item.requiredInputs} tone="blue" /><h4>Workflow</h4><KnowledgeChain nodes={item.workflow} /><div className="capstone-two-column"><div><h4>Formulas</h4><BadgeList items={item.formulas} tone="green" /></div><div><h4>Models</h4><BadgeList items={item.models} tone="purple" /></div></div><h4>Outputs</h4><BadgeList items={item.outputs} tone="amber" /><h4>Deliverables</h4><ul>{item.deliverables.map((x)=><li key={x}>{x}</li>)}</ul><h4>Evaluation criteria</h4><ul>{item.evaluationCriteria.map((x)=><li key={x}>{x}</li>)}</ul><h4>Connected modules</h4><BadgeList items={item.connectedModules} tone="blue" /><h4>Practice links</h4><BadgeList items={item.practiceLinks} tone="purple" /><div className="mini-result warning"><strong>Portfolio use:</strong> {item.portfolioUse}</div></article> }
function CapstoneSelect({ label, value, values, onChange }: { label: string; value: string; values: string[]; onChange: (value: string) => void }) { return <label className="library-select"><span>{label}</span><select value={value} onChange={(event) => onChange(event.target.value)}>{values.map((item)=><option key={item} value={item}>{item}</option>)}</select></label> }
