import { useMemo, useState } from 'react'
import { creditPromotionItems, creditPromotionSummary } from '../data/creditPromotionQueue'
import type { CreditPromotionItem } from '../types/creditPromotion'
import { BadgeList } from '../components/ui/BadgeList'
import { KnowledgeChain } from '../components/knowledge/KnowledgeChain'

interface Props { focusId?: string | null }
const allValue = 'All'
const statusOptions = [allValue, ...Array.from(new Set(creditPromotionItems.map((x) => x.status))).sort()]
const targetOptions = [allValue, ...Array.from(new Set(creditPromotionItems.map((x) => x.target))).sort()]

export function CreditPromotionQueuePage({ focusId }: Props) {
  const [status, setStatus] = useState(allValue)
  const [target, setTarget] = useState(allValue)
  const [query, setQuery] = useState('')
  const visible = useMemo(() => { const q = query.trim().toLowerCase(); return creditPromotionItems.filter((x) => status === allValue || x.status === status).filter((x) => target === allValue || x.target === target).filter((x) => !q || [x.title,x.status,x.target,x.sourceSection,x.sourceFile,x.proposedUpdate,x.reason,x.risk,x.ownerView,x.nextAction,...x.evidenceNeed,...x.linkedLessons,...x.linkedArtifacts].join(' ').toLowerCase().includes(q)).sort((a,b)=>(a.id===focusId?-1:b.id===focusId?1:a.target.localeCompare(b.target)||a.title.localeCompare(b.title))) }, [focusId, query, status, target])
  return <section className="page-stack">{focusId && <div className="deep-link-banner">Opened from Search · focused promotion item</div>}<div className="hero-panel credit-promotion-hero"><div><span className="eyebrow">Sprint 5.3 · Credit Scoring Promotion Queue</span><h1>Decide what moves from review into the Hub.</h1><p>Controlled queue for Banking Study, Output Atlas, Formula Library, Interview Prep, Portfolio Builder and Practice Engine.</p></div><div className="credit-promotion-score-card"><span className="eyebrow">Queue</span><strong>{creditPromotionSummary.total}</strong><p>{creditPromotionSummary.promoteAfterRefs} promote after refs · {creditPromotionSummary.hold} hold</p><div className="inventory-mini-stats"><span>{creditPromotionSummary.complement} complement</span><span>{creditPromotionSummary.reject} reject</span></div></div></div><section className="manual-panel warning"><span className="eyebrow">Promotion rule</span><h2>Promotion is conditional.</h2><p>Items can move only after page refs, evidence limits and review decisions are recorded.</p></section><section className="manual-panel result-impact"><span className="eyebrow">Decision Flow</span><h2>Review section → evidence need → target view → proposed update → decision</h2><KnowledgeChain nodes={['Review Section','Evidence Need','Target View','Proposed Update','Risk Check','Promotion Decision']} /></section><section className="manual-panel inventory-filter-panel"><div className="library-filter-header"><div><span className="eyebrow">Queue Filters</span><h2>{visible.length} of {creditPromotionItems.length} items visible</h2></div><button className="text-button" onClick={() => { setStatus(allValue); setTarget(allValue); setQuery('') }} type="button">Clear filters</button></div><input className="library-search-input" value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search validation, target definition, score bands, interview, Output Atlas..." /><div className="library-filter-grid"><Select label="Status" value={status} values={statusOptions} onChange={setStatus} /><Select label="Target" value={target} values={targetOptions} onChange={setTarget} /></div></section><section className="credit-promotion-grid">{visible.map((x) => <Card key={x.id} item={x} focused={x.id === focusId} />)}</section></section>
}
function Card({ item, focused }: { item: CreditPromotionItem; focused: boolean }) { const cls = item.status.toLowerCase().split(' ').join('-'); return <article className={`credit-promotion-card ${focused ? 'focused-result-card' : ''}`}><div className="credit-promotion-card-top"><span className="eyebrow">{item.target}</span><span className={`credit-promotion-pill ${cls}`}>{item.status}</span></div><h3>{item.title}</h3><p><strong>Source:</strong> {item.sourceSection} · {item.sourceFile}</p><div className="mini-result good"><strong>Proposed update:</strong> {item.proposedUpdate}</div><div className="mini-result warning"><strong>Risk:</strong> {item.risk}</div><h4>Evidence needed</h4><BadgeList items={item.evidenceNeed} tone="amber" /><h4>Reason</h4><p>{item.reason}</p><h4>Owner view</h4><BadgeList items={[item.ownerView]} tone="purple" /><h4>Linked lessons</h4><BadgeList items={item.linkedLessons} tone="blue" /><h4>Linked artifacts</h4><BadgeList items={item.linkedArtifacts} tone="green" /><h4>Next action</h4><KnowledgeChain nodes={[item.nextAction]} /></article> }
function Select({ label, value, values, onChange }: { label:string; value:string; values:string[]; onChange:(v:string)=>void }) { return <label className="library-select"><span>{label}</span><select value={value} onChange={(e)=>onChange(e.target.value)}>{values.map((x)=><option key={x} value={x}>{x}</option>)}</select></label> }
