import { useMemo, useState } from 'react'
import { creditReviewSections, creditReviewSummary } from '../data/creditReview'
import type { CreditReviewSection } from '../types/creditReview'
import { BadgeList } from '../components/ui/BadgeList'
import { KnowledgeChain } from '../components/knowledge/KnowledgeChain'

interface Props { focusId?: string | null }
const allValue = 'All'
const statusOptions = [allValue, ...Array.from(new Set(creditReviewSections.map((x) => x.status))).sort()]

export function CreditScoringReviewPage({ focusId }: Props) {
  const [status, setStatus] = useState(allValue)
  const [query, setQuery] = useState('')
  const visible = useMemo(() => { const q = query.trim().toLowerCase(); return creditReviewSections.filter((x) => status === allValue || x.status === status).filter((x) => !q || [x.title,x.status,x.sourceFile,x.extractedPoint,x.evidenceLimit,x.promotionAction,...x.pageRefs,...x.targetLessons,...x.targetArtifacts,...x.qualityChecks].join(' ').toLowerCase().includes(q)).sort((a,b)=>(a.id===focusId?-1:b.id===focusId?1:a.title.localeCompare(b.title))) }, [focusId, query, status])
  return <section className="page-stack">{focusId && <div className="deep-link-banner">Opened from Search · focused credit review section</div>}<div className="hero-panel credit-review-hero"><div><span className="eyebrow">Sprint 5.2 · Credit Scoring Review</span><h1>RetailCreditScoring.pdf review pass.</h1><p>Controlled sections for target definition, lending data, model score, validation, decision policy and monitoring.</p></div><div className="credit-review-score-card"><span className="eyebrow">Review Sections</span><strong>{creditReviewSummary.total}</strong><p>{creditReviewSummary.needsRefs} need refs · {creditReviewSummary.promotionReview} promotion review</p><div className="inventory-mini-stats"><span>{creditReviewSummary.candidates} candidates</span><span>controlled</span></div></div></div><section className="manual-panel warning"><span className="eyebrow">Review rule</span><h2>No final promotion without page refs.</h2><p>Every card keeps limits explicit until exact evidence is logged.</p></section><section className="manual-panel result-impact"><span className="eyebrow">Review Flow</span><h2>Problem → target → ABT → score → validation → policy → monitoring</h2><KnowledgeChain nodes={['Problem','Target','ABT','Score','Validation','Policy','Monitoring']} /></section><section className="manual-panel inventory-filter-panel"><div className="library-filter-header"><div><span className="eyebrow">Filters</span><h2>{visible.length} of {creditReviewSections.length} sections visible</h2></div><button className="text-button" onClick={() => { setStatus(allValue); setQuery('') }} type="button">Clear filters</button></div><input className="library-search-input" value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search target, validation, score bands, ABT or monitoring..." /><div className="library-filter-grid"><Select label="Status" value={status} values={statusOptions} onChange={setStatus} /></div></section><section className="credit-review-grid">{visible.map((x) => <Card key={x.id} item={x} focused={x.id === focusId} />)}</section></section>
}
function Card({ item, focused }: { item: CreditReviewSection; focused: boolean }) { const cls = item.status.toLowerCase().split(' ').join('-'); return <article className={`credit-review-card ${focused ? 'focused-result-card' : ''}`}><div className="credit-review-card-top"><span className="eyebrow">{item.sourceFile}</span><span className={`credit-review-pill ${cls}`}>{item.status}</span></div><h3>{item.title}</h3><p><strong>File ID:</strong> {item.fileId}</p><div className="mini-result good"><strong>Point:</strong> {item.extractedPoint}</div><div className="mini-result warning"><strong>Limit:</strong> {item.evidenceLimit}</div><h4>Page refs</h4><BadgeList items={item.pageRefs} tone="amber" /><h4>Target lessons</h4><BadgeList items={item.targetLessons} tone="purple" /><h4>Artifacts</h4><BadgeList items={item.targetArtifacts} tone="blue" /><h4>Promotion action</h4><p>{item.promotionAction}</p><h4>Checks</h4><ul>{item.qualityChecks.map((x)=><li key={x}>{x}</li>)}</ul></article> }
function Select({ label, value, values, onChange }: { label:string; value:string; values:string[]; onChange:(v:string)=>void }) { return <label className="library-select"><span>{label}</span><select value={value} onChange={(e)=>onChange(e.target.value)}>{values.map((x)=><option key={x} value={x}>{x}</option>)}</select></label> }
