import { useMemo, useState } from 'react'
import { hubQAChecks, hubQASummary } from '../data/hubQualityPolish'
import type { HubQACheck } from '../types/hubQuality'
import { BadgeList } from '../components/ui/BadgeList'
import { KnowledgeChain } from '../components/knowledge/KnowledgeChain'

interface HubQAPolishPageProps { focusId?: string | null }
const allValue = 'All'
const areaOptions = [allValue, ...Array.from(new Set(hubQAChecks.map((item) => item.area))).sort()]
const statusOptions = [allValue, ...Array.from(new Set(hubQAChecks.map((item) => item.status))).sort()]

export function HubQAPolishPage({ focusId }: HubQAPolishPageProps) {
  const [area, setArea] = useState(allValue)
  const [status, setStatus] = useState(allValue)
  const [query, setQuery] = useState('')
  const visible = useMemo(() => { const q = query.trim().toLowerCase(); return hubQAChecks.filter((item) => area === allValue || item.area === area).filter((item) => status === allValue || item.status === status).filter((item) => !q || [item.title,item.area,item.status,item.whyItMatters,item.ownerLayer,...item.checkedSignals,...item.risks,...item.polishActions,...item.linkedViews].join(' ').toLowerCase().includes(q)).sort((a,b)=>(a.id===focusId?-1:b.id===focusId?1:b.score-a.score||a.title.localeCompare(b.title))) }, [area, focusId, query, status])
  return <section className="page-stack">{focusId && <div className="deep-link-banner">Opened from Global Search · focused QA check</div>}<div className="hero-panel hub-qa-hero"><div><span className="eyebrow">Sprint 4.9 · Final Hub QA & Navigation Polish</span><h1>Final control layer for navigation, search, UX and governance.</h1><p>This page keeps the Knowledge Hub clean: study-first, searchable, evidence-aware and ready for professional use.</p></div><div className="hub-qa-score-card"><span className="eyebrow">Hub QA Score</span><strong>{hubQASummary.avgScore}%</strong><p>{hubQASummary.total} checks · {hubQASummary.ready} ready</p><div className="inventory-mini-stats"><span>{hubQASummary.watch} watch</span><span>{hubQASummary.needsReview} review</span></div></div></div><section className="manual-panel result-impact"><span className="eyebrow">Quality Flow</span><h2>Study-first UX → search coverage → route health → evidence discipline → career readiness</h2><KnowledgeChain nodes={['Study-first UX','Navigation','Search Coverage','Route Health','Evidence Discipline','Career Readiness']} /></section><section className="manual-panel inventory-filter-panel"><div className="library-filter-header"><div><span className="eyebrow">QA Filters</span><h2>{visible.length} of {hubQAChecks.length} checks visible</h2></div><button className="text-button" onClick={() => { setArea(allValue); setStatus(allValue); setQuery('') }} type="button">Clear filters</button></div><input className="library-search-input" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search navigation, search, route, evidence, career, validate or UX..." /><div className="library-filter-grid"><HubQASelect label="Area" value={area} values={areaOptions} onChange={setArea} /><HubQASelect label="Status" value={status} values={statusOptions} onChange={setStatus} /></div></section><section className="hub-qa-grid">{visible.map((item) => <HubQACard key={item.id} item={item} focused={item.id === focusId} />)}</section></section>
}
function HubQACard({ item, focused }: { item: HubQACheck; focused: boolean }) { const statusClass = item.status.toLowerCase().split(' ').join('-'); return <article className={`hub-qa-card ${focused ? 'focused-result-card' : ''}`}><div className="hub-qa-card-top"><span className="eyebrow">{item.area}</span><span className={`hub-qa-pill ${statusClass}`}>{item.status}</span></div><div className="hub-qa-score-row"><h3>{item.title}</h3><strong>{item.score}%</strong></div><p>{item.whyItMatters}</p><div className="mini-result good"><strong>Owner layer:</strong> {item.ownerLayer}</div><h4>Checked signals</h4><BadgeList items={item.checkedSignals} tone="blue" /><h4>Risks</h4><ul>{item.risks.map((x)=><li key={x}>{x}</li>)}</ul><h4>Polish actions</h4><KnowledgeChain nodes={item.polishActions} /><h4>Linked views</h4><BadgeList items={item.linkedViews} tone="purple" /></article> }
function HubQASelect({ label, value, values, onChange }: { label: string; value: string; values: string[]; onChange: (value: string) => void }) { return <label className="library-select"><span>{label}</span><select value={value} onChange={(event) => onChange(event.target.value)}>{values.map((item)=><option key={item} value={item}>{item}</option>)}</select></label> }
