import { useMemo, useState } from 'react'
import { interviewPrompts, interviewPrepSummary } from '../data/interviewPrep'
import type { InterviewPrompt } from '../types/interviewPrep'
import { BadgeList } from '../components/ui/BadgeList'
import { KnowledgeChain } from '../components/knowledge/KnowledgeChain'

interface InterviewPrepPageProps { focusId?: string | null }
const allValue = 'All'
const areaOptions = [allValue, ...Array.from(new Set(interviewPrompts.map((item) => item.area))).sort()]
const formatOptions = [allValue, ...Array.from(new Set(interviewPrompts.map((item) => item.format))).sort()]

export function InterviewPrepPage({ focusId }: InterviewPrepPageProps) {
  const [area, setArea] = useState(allValue)
  const [format, setFormat] = useState(allValue)
  const [query, setQuery] = useState('')
  const visible = useMemo(() => { const q = query.trim().toLowerCase(); return interviewPrompts.filter((item) => area === allValue || item.area === area).filter((item) => format === allValue || item.format === format).filter((item) => !q || [item.title,item.area,item.format,item.level,item.question,item.whyItMatters,item.sampleAnswer,...item.answerFramework,...item.followUps,...item.linkedPortfolioItems,...item.linkedCapstones,...item.skillsTested,...item.redFlags].join(' ').toLowerCase().includes(q)).sort((a,b)=>(a.id===focusId?-1:b.id===focusId?1:a.area.localeCompare(b.area)||a.title.localeCompare(b.title))) }, [area, focusId, format, query])
  return <section className="page-stack">{focusId && <div className="deep-link-banner">Opened from Global Search · focused interview prompt</div>}<div className="hero-panel interview-hero"><div><span className="eyebrow">Sprint 4.7 · Interview Prep Engine</span><h1>Defend your portfolio, projects and technical thinking.</h1><p>Practice behavioral, technical, case and project-defense questions connected directly to your capstones and portfolio stories.</p></div><div className="interview-score-card"><span className="eyebrow">Interview Bank</span><strong>{interviewPrepSummary.total}</strong><p>{interviewPrepSummary.star} STAR · {interviewPrepSummary.projectDefense} defenses</p><div className="inventory-mini-stats"><span>{interviewPrepSummary.technical} technical</span><span>{interviewPrepSummary.caseQuestions} cases</span></div></div></div><section className="manual-panel result-impact"><span className="eyebrow">Interview Flow</span><h2>Question → framework → answer → follow-ups → red flags → portfolio proof</h2><KnowledgeChain nodes={['Question','Framework','Sample Answer','Follow-ups','Red Flags','Portfolio Proof']} /></section><section className="manual-panel inventory-filter-panel"><div className="library-filter-header"><div><span className="eyebrow">Interview Filters</span><h2>{visible.length} of {interviewPrompts.length} prompts visible</h2></div><button className="text-button" onClick={() => { setArea(allValue); setFormat(allValue); setQuery('') }} type="button">Clear filters</button></div><input className="library-search-input" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search SQL, valuation, market brief, STAR, project defense, CFA or banking..." /><div className="library-filter-grid"><InterviewSelect label="Area" value={area} values={areaOptions} onChange={setArea} /><InterviewSelect label="Format" value={format} values={formatOptions} onChange={setFormat} /></div></section><section className="interview-grid">{visible.map((item) => <InterviewCard key={item.id} item={item} focused={item.id === focusId} />)}</section></section>
}
function InterviewCard({ item, focused }: { item: InterviewPrompt; focused: boolean }) { const [revealed, setRevealed] = useState(false); return <article className={`interview-card ${focused ? 'focused-result-card' : ''}`}><div className="interview-card-top"><span className="eyebrow">{item.area} · {item.level}</span><span className="interview-pill">{item.format}</span></div><h3>{item.title}</h3><div className="interview-question"><strong>Question</strong><span>{item.question}</span></div><p>{item.whyItMatters}</p><h4>Answer framework</h4><KnowledgeChain nodes={item.answerFramework} /><button className="primary-button" onClick={() => setRevealed((value) => !value)} type="button">{revealed ? 'Hide sample answer' : 'Reveal sample answer'}</button>{revealed && <div className="interview-answer"><h4>Sample answer</h4><p>{item.sampleAnswer}</p></div>}<h4>Follow-up questions</h4><ul>{item.followUps.map((x)=><li key={x}>{x}</li>)}</ul><h4>Skills tested</h4><BadgeList items={item.skillsTested} tone="blue" /><h4>Linked portfolio proof</h4><BadgeList items={item.linkedPortfolioItems} tone="green" /><h4>Linked capstones</h4><BadgeList items={item.linkedCapstones} tone="purple" /><h4>Red flags to avoid</h4><BadgeList items={item.redFlags} tone="amber" /></article> }
function InterviewSelect({ label, value, values, onChange }: { label: string; value: string; values: string[]; onChange: (value: string) => void }) { return <label className="library-select"><span>{label}</span><select value={value} onChange={(event) => onChange(event.target.value)}>{values.map((item)=><option key={item} value={item}>{item}</option>)}</select></label> }
