import { useMemo, useState } from 'react'
import { lcFieldGroups, lcFieldMapSummary } from '../data/lcFieldMap'
import type { LCFieldGroup } from '../types/lcFieldMap'
import { BadgeList } from '../components/ui/BadgeList'
import { KnowledgeChain } from '../components/knowledge/KnowledgeChain'

interface Props { focusId?: string | null }
const allValue = 'All'
const statusOptions = [allValue, ...Array.from(new Set(lcFieldGroups.map((x) => x.status))).sort()]
const groupOptions = [allValue, ...Array.from(new Set(lcFieldGroups.map((x) => x.group))).sort()]

export function LCFieldMappingPage({ focusId }: Props) {
  const [status, setStatus] = useState(allValue)
  const [group, setGroup] = useState(allValue)
  const [query, setQuery] = useState('')
  const visible = useMemo(() => { const q = query.trim().toLowerCase(); return lcFieldGroups.filter((x) => status === allValue || x.status === status).filter((x) => group === allValue || x.group === group).filter((x) => !q || [x.title,x.status,x.group,x.purpose,x.nextAction,...x.fieldCandidates,...x.evidenceNeed,...x.dataQualityChecks,...x.leakageRisks,...x.featureUse,...x.targetLessons].join(' ').toLowerCase().includes(q)).sort((a,b)=>(a.id===focusId?-1:b.id===focusId?1:a.group.localeCompare(b.group)||a.title.localeCompare(b.title))) }, [focusId, group, query, status])
  return <section className="page-stack">{focusId && <div className="deep-link-banner">Opened from Search · focused field group</div>}<div className="hero-panel lc-field-hero"><div><span className="eyebrow">Sprint 5.5 · LC Field Mapping</span><h1>Map lending dictionary fields into ABT groups and quality checks.</h1><p>Field names remain candidates until the spreadsheet is reviewed row by row.</p></div><div className="lc-field-score-card"><span className="eyebrow">Field Groups</span><strong>{lcFieldMapSummary.total}</strong><p>{lcFieldMapSummary.pendingRefs} pending refs · {lcFieldMapSummary.candidate} candidates</p><div className="inventory-mini-stats"><span>{lcFieldMapSummary.ready} ready</span><span>ABT</span></div></div></div><section className="manual-panel warning"><span className="eyebrow">Dataset rule</span><h2>No final field evidence before sheet review.</h2><p>This map organizes field groups, quality checks and study links without claiming final spreadsheet approval.</p></section><section className="manual-panel result-impact"><span className="eyebrow">Mapping Flow</span><h2>Dictionary → group → quality check → feature use → study update</h2><KnowledgeChain nodes={['Dictionary','Field Group','Quality Check','Feature Use','Study Update']} /></section><section className="manual-panel inventory-filter-panel"><div className="library-filter-header"><div><span className="eyebrow">Filters</span><h2>{visible.length} of {lcFieldGroups.length} groups visible</h2></div><button className="text-button" onClick={() => { setStatus(allValue); setGroup(allValue); setQuery('') }} type="button">Clear filters</button></div><input className="library-search-input" value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search borrower, target, field, date, score, quality..." /><div className="library-filter-grid"><Select label="Status" value={status} values={statusOptions} onChange={setStatus} /><Select label="Group" value={group} values={groupOptions} onChange={setGroup} /></div></section><section className="lc-field-grid">{visible.map((x) => <Card key={x.id} item={x} focused={x.id === focusId} />)}</section></section>
}
function Card({ item, focused }: { item: LCFieldGroup; focused: boolean }) { const cls = item.status.toLowerCase().split(' ').join('-'); return <article className={`lc-field-card ${focused ? 'focused-result-card' : ''}`}><div className="lc-field-card-top"><span className="eyebrow">{item.group}</span><span className={`lc-field-pill ${cls}`}>{item.status}</span></div><h3>{item.title}</h3><p>{item.purpose}</p><h4>Field candidates</h4><BadgeList items={item.fieldCandidates} tone="blue" /><h4>Evidence needed</h4><BadgeList items={item.evidenceNeed} tone="amber" /><h4>Quality checks</h4><BadgeList items={item.dataQualityChecks} tone="green" /><h4>Risk notes</h4><ul>{item.leakageRisks.map((x)=><li key={x}>{x}</li>)}</ul><h4>Feature use</h4><BadgeList items={item.featureUse} tone="purple" /><h4>Study links</h4><BadgeList items={item.targetLessons} tone="blue" /><h4>Next action</h4><KnowledgeChain nodes={[item.nextAction]} /></article> }
function Select({ label, value, values, onChange }: { label:string; value:string; values:string[]; onChange:(v:string)=>void }) { return <label className="library-select"><span>{label}</span><select value={value} onChange={(e)=>onChange(e.target.value)}>{values.map((x)=><option key={x} value={x}>{x}</option>)}</select></label> }
