import { useMemo, useState } from 'react'
import { managementLessons, managementStudySummary } from '../data/managementStudy'
import type { ManagementLesson } from '../types/managementStudy'
import { BadgeList } from '../components/ui/BadgeList'
import { KnowledgeChain } from '../components/knowledge/KnowledgeChain'

interface ManagementStrategyStudyPageProps { focusId?: string | null }
const allValue = 'All'
const levelOptions = [allValue, ...Array.from(new Set(managementLessons.map((lesson) => lesson.level))).sort()]
const statusOptions = [allValue, ...Array.from(new Set(managementLessons.map((lesson) => lesson.status))).sort()]

export function ManagementStrategyStudyPage({ focusId }: ManagementStrategyStudyPageProps) {
  const [level, setLevel] = useState(allValue)
  const [status, setStatus] = useState(allValue)
  const [query, setQuery] = useState('')
  const lessons = useMemo(() => {
    const q = query.trim().toLowerCase()
    return managementLessons.filter((lesson) => level === allValue || lesson.level === level).filter((lesson) => status === allValue || lesson.status === status).filter((lesson) => !q || [lesson.title, lesson.level, lesson.status, lesson.objective, ...lesson.materials, ...lesson.concepts, ...lesson.workflow, ...lesson.frameworks, ...lesson.outputs, ...lesson.interpretation, ...lesson.decisions, ...lesson.practice, ...lesson.connections].join(' ').toLowerCase().includes(q)).sort((a, b) => (a.id === focusId ? -1 : b.id === focusId ? 1 : levelRank(a.level) - levelRank(b.level) || a.title.localeCompare(b.title)))
  }, [focusId, level, query, status])
  return <section className="page-stack">{focusId && <div className="deep-link-banner">Opened from Global Search · focused management lesson</div>}<div className="hero-panel management-study-hero"><div><span className="eyebrow">Sprint 3.9 · Management & Strategy Study Module</span><h1>Management learning for strategy, competition, business models and execution.</h1><p>This module turns management frameworks into decision-ready workflows, outputs and practice for professional business situations.</p></div><div className="management-study-score-card"><span className="eyebrow">Study Module</span><strong>{managementStudySummary.totalLessons}</strong><p>{managementStudySummary.frameworks} frameworks · {managementStudySummary.outputs} outputs</p><div className="inventory-mini-stats"><span>{managementStudySummary.practicePrompts} prompts</span><span>{managementStudySummary.candidates} candidates</span></div></div></div><section className="manual-panel result-impact"><span className="eyebrow">Study Flow</span><h2>From framework to strategic decision</h2><KnowledgeChain nodes={['Business Problem', 'Framework', 'Diagnosis', 'Output', 'Decision', 'Execution', 'Practice']} /></section><section className="manual-panel inventory-filter-panel"><div className="library-filter-header"><div><span className="eyebrow">Lesson Filters</span><h2>{lessons.length} of {managementLessons.length} lessons visible</h2></div><button className="text-button" onClick={() => { setLevel(allValue); setStatus(allValue); setQuery('') }} type="button">Clear filters</button></div><input className="library-search-input" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search SWOT, PESTEL, Porter, business model, operations or KPIs..." /><div className="library-filter-grid"><StudySelect label="Level" value={level} values={levelOptions} onChange={setLevel} /><StudySelect label="Status" value={status} values={statusOptions} onChange={setStatus} /></div></section><section className="manual-panel"><span className="eyebrow">Management Lessons</span><h2>Learn frameworks through workflows, outputs and decisions</h2><div className="management-study-grid">{lessons.map((lesson) => <LessonCard key={lesson.id} lesson={lesson} focused={lesson.id === focusId} />)}</div></section></section>
}

function LessonCard({ lesson, focused }: { lesson: ManagementLesson; focused: boolean }) {
  return <article className={`management-study-card ${focused ? 'focused-result-card' : ''}`}><div className="management-study-card-top"><span className="eyebrow">{lesson.level} · {lesson.status}</span><span className={`management-study-pill status-${lesson.status.toLowerCase().replaceAll(' ', '-')}`}>{lesson.status}</span></div><h3>{lesson.title}</h3><p>{lesson.objective}</p><h4>Materials</h4><BadgeList items={lesson.materials} tone="blue" /><h4>Core concepts</h4><BadgeList items={lesson.concepts} tone="purple" /><h4>Professional workflow</h4><ol>{lesson.workflow.map((step) => <li key={step}>{step}</li>)}</ol><h4>Frameworks and outputs</h4><BadgeList items={[...lesson.frameworks, ...lesson.outputs]} tone="green" /><h4>How to interpret</h4><ul>{lesson.interpretation.map((item) => <li key={item}>{item}</li>)}</ul><h4>Business decisions</h4><BadgeList items={lesson.decisions} tone="amber" /><h4>Practice prompts</h4><ul>{lesson.practice.map((prompt) => <li key={prompt}>{prompt}</li>)}</ul><h4>Connected areas</h4><BadgeList items={lesson.connections} tone="blue" /></article>
}
function StudySelect({ label, value, values, onChange }: { label: string; value: string; values: string[]; onChange: (value: string) => void }) { return <label className="library-select"><span>{label}</span><select value={value} onChange={(event) => onChange(event.target.value)}>{values.map((item) => <option key={item} value={item}>{item}</option>)}</select></label> }
function levelRank(level: ManagementLesson['level']) { if (level === 'Foundation') return 1; if (level === 'Applied') return 2; return 3 }
