import { useMemo, useState } from 'react'
import { portfolioItems, portfolioSummary } from '../data/portfolioBuilder'
import type { PortfolioItem } from '../types/portfolioBuilder'
import { BadgeList } from '../components/ui/BadgeList'

interface PortfolioBuilderPageProps { focusId?: string | null }
const allValue = 'All'
const areaOptions = [allValue, ...Array.from(new Set(portfolioItems.map((item) => item.area))).sort()]
const levelOptions = [allValue, ...Array.from(new Set(portfolioItems.map((item) => item.level))).sort()]

export function PortfolioBuilderPage({ focusId }: PortfolioBuilderPageProps) {
  const [area, setArea] = useState(allValue)
  const [level, setLevel] = useState(allValue)
  const [query, setQuery] = useState('')
  const visible = useMemo(() => { const q = query.trim().toLowerCase(); return portfolioItems.filter((item) => area === allValue || item.area === area).filter((item) => level === allValue || item.level === level).filter((item) => !q || [item.title,item.area,item.level,item.projectSummary,item.cvDescription,item.linkedinDescription,item.portfolioHeadline,...item.skills,...item.tools,...item.outputs,...item.evidence,...item.interviewTalkingPoints,...item.nextUpgrade].join(' ').toLowerCase().includes(q)).sort((a,b)=>(a.id===focusId?-1:b.id===focusId?1:a.area.localeCompare(b.area)||a.title.localeCompare(b.title))) }, [area, focusId, level, query])
  return <section className="page-stack">{focusId && <div className="deep-link-banner">Opened from Global Search · focused portfolio item</div>}<div className="hero-panel portfolio-hero"><div><span className="eyebrow">Sprint 4.6 · Portfolio Builder</span><h1>Turn capstones into a professional portfolio story.</h1><p>Each portfolio item packages a capstone into skills, tools, outputs, proof points, interview talking points and CV / LinkedIn descriptions.</p></div><div className="portfolio-score-card"><span className="eyebrow">Portfolio Assets</span><strong>{portfolioSummary.total}</strong><p>{portfolioSummary.skills} skills · {portfolioSummary.outputs} outputs</p><div className="inventory-mini-stats"><span>{portfolioSummary.tools} tools</span><span>CV ready</span></div></div></div><section className="manual-panel result-impact"><span className="eyebrow">Portfolio Flow</span><h2>Capstone → skills → outputs → evidence → talking points → CV / LinkedIn</h2></section><section className="manual-panel inventory-filter-panel"><div className="library-filter-header"><div><span className="eyebrow">Portfolio Filters</span><h2>{visible.length} of {portfolioItems.length} portfolio items visible</h2></div><button className="text-button" onClick={() => { setArea(allValue); setLevel(allValue); setQuery('') }} type="button">Clear filters</button></div><input className="library-search-input" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search analytics, banking, finance, markets, strategy, CFA or Bloomberg..." /><div className="library-filter-grid"><PortfolioSelect label="Area" value={area} values={areaOptions} onChange={setArea} /><PortfolioSelect label="Level" value={level} values={levelOptions} onChange={setLevel} /></div></section><section className="portfolio-grid">{visible.map((item) => <PortfolioCard key={item.id} item={item} focused={item.id === focusId} />)}</section></section>
}
function PortfolioCard({ item, focused }: { item: PortfolioItem; focused: boolean }) { return <article className={`portfolio-card ${focused ? 'focused-result-card' : ''}`}><div className="portfolio-card-top"><span className="eyebrow">{item.area} · {item.level}</span><span className="portfolio-pill">{item.capstoneId}</span></div><h3>{item.title}</h3><p>{item.projectSummary}</p><div className="mini-result good"><strong>Headline:</strong> {item.portfolioHeadline}</div><h4>Skills demonstrated</h4><BadgeList items={item.skills} tone="blue" /><h4>Tools used</h4><BadgeList items={item.tools} tone="purple" /><h4>Outputs produced</h4><BadgeList items={item.outputs} tone="green" /><h4>Evidence to show</h4><ul>{item.evidence.map((x)=><li key={x}>{x}</li>)}</ul><h4>Interview talking points</h4><ul>{item.interviewTalkingPoints.map((x)=><li key={x}>{x}</li>)}</ul><div className="portfolio-copy-block"><h4>CV description</h4><p>{item.cvDescription}</p></div><div className="portfolio-copy-block"><h4>LinkedIn description</h4><p>{item.linkedinDescription}</p></div><h4>Next upgrade</h4><BadgeList items={item.nextUpgrade} tone="amber" /></article> }
function PortfolioSelect({ label, value, values, onChange }: { label: string; value: string; values: string[]; onChange: (value: string) => void }) { return <label className="library-select"><span>{label}</span><select value={value} onChange={(event) => onChange(event.target.value)}>{values.map((item)=><option key={item} value={item}>{item}</option>)}</select></label> }
