import { useMemo, useState } from 'react'
import { careerRoles, roleReadinessSummary } from '../data/roleReadiness'
import type { CareerRole } from '../types/roleReadiness'
import { BadgeList } from '../components/ui/BadgeList'
import { KnowledgeChain } from '../components/knowledge/KnowledgeChain'

interface RoleReadinessPageProps { focusId?: string | null }
const allValue = 'All'
const areaOptions = [allValue, ...Array.from(new Set(careerRoles.map((item) => item.area))).sort()]
const bandOptions = [allValue, ...Array.from(new Set(careerRoles.map((item) => item.readinessBand))).sort()]

export function RoleReadinessPage({ focusId }: RoleReadinessPageProps) {
  const [area, setArea] = useState(allValue)
  const [band, setBand] = useState(allValue)
  const [query, setQuery] = useState('')
  const visible = useMemo(() => { const q = query.trim().toLowerCase(); return careerRoles.filter((item) => area === allValue || item.area === area).filter((item) => band === allValue || item.readinessBand === band).filter((item) => !q || [item.title,item.area,item.readinessBand,item.roleSummary,item.resumeAngle,...item.coreSkills,...item.proofAssets,...item.capstones,...item.portfolioItems,...item.interviewPrompts,...item.gaps,...item.nextActions,...item.studyModules,...item.formulas,...item.outputs,...item.tools].join(' ').toLowerCase().includes(q)).sort((a,b)=>(a.id===focusId?-1:b.id===focusId?1:b.readinessScore-a.readinessScore||a.title.localeCompare(b.title))) }, [area, band, focusId, query])
  return <section className="page-stack">{focusId && <div className="deep-link-banner">Opened from Global Search · focused role readiness card</div>}<div className="hero-panel role-hero"><div><span className="eyebrow">Sprint 4.8 · Career Roadmap & Role Readiness</span><h1>Map your Hub evidence to real professional roles.</h1><p>Each role connects study modules, capstones, portfolio stories, interview prompts, skill gaps and next learning actions.</p></div><div className="role-score-card"><span className="eyebrow">Role Map</span><strong>{roleReadinessSummary.avgScore}%</strong><p>{roleReadinessSummary.total} roles · {roleReadinessSummary.interviewReady} interview-ready</p><div className="inventory-mini-stats"><span>{roleReadinessSummary.portfolioReady} portfolio-ready</span><span>gap map</span></div></div></div><section className="manual-panel result-impact"><span className="eyebrow">Readiness Flow</span><h2>Role → skills → proof assets → gaps → next actions → interview story</h2><KnowledgeChain nodes={['Target Role','Core Skills','Proof Assets','Skills Gap','Next Actions','Interview Story']} /></section><section className="manual-panel inventory-filter-panel"><div className="library-filter-header"><div><span className="eyebrow">Role Filters</span><h2>{visible.length} of {careerRoles.length} roles visible</h2></div><button className="text-button" onClick={() => { setArea(allValue); setBand(allValue); setQuery('') }} type="button">Clear filters</button></div><input className="library-search-input" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search Data Analyst, Finance Analyst, Strategy, CFA, skills gap or next actions..." /><div className="library-filter-grid"><RoleSelect label="Area" value={area} values={areaOptions} onChange={setArea} /><RoleSelect label="Readiness" value={band} values={bandOptions} onChange={setBand} /></div></section><section className="role-grid">{visible.map((role) => <RoleCard key={role.id} role={role} focused={role.id === focusId} />)}</section></section>
}
function RoleCard({ role, focused }: { role: CareerRole; focused: boolean }) { const bandClass = role.readinessBand.toLowerCase().split(' ').join('-'); return <article className={`role-card ${focused ? 'focused-result-card' : ''}`}><div className="role-card-top"><span className="eyebrow">{role.area}</span><span className={`role-pill ${bandClass}`}>{role.readinessBand}</span></div><div className="role-score-row"><h3>{role.title}</h3><strong>{role.readinessScore}%</strong></div><p>{role.roleSummary}</p><div className="mini-result good"><strong>Resume angle:</strong> {role.resumeAngle}</div><h4>Core skills</h4><BadgeList items={role.coreSkills} tone="blue" /><h4>Proof assets</h4><BadgeList items={role.proofAssets} tone="green" /><div className="role-two-column"><div><h4>Capstones</h4><BadgeList items={role.capstones} tone="purple" /></div><div><h4>Portfolio items</h4><BadgeList items={role.portfolioItems} tone="amber" /></div></div><h4>Interview prompts</h4><BadgeList items={role.interviewPrompts} tone="blue" /><h4>Skills gap</h4><ul>{role.gaps.map((x)=><li key={x}>{x}</li>)}</ul><h4>Next learning actions</h4><KnowledgeChain nodes={role.nextActions} /><h4>Study modules</h4><BadgeList items={role.studyModules} tone="purple" /><div className="role-two-column"><div><h4>Formulas</h4><BadgeList items={role.formulas} tone="green" /></div><div><h4>Outputs</h4><BadgeList items={role.outputs} tone="amber" /></div></div><h4>Tools</h4><BadgeList items={role.tools} tone="blue" /></article> }
function RoleSelect({ label, value, values, onChange }: { label: string; value: string; values: string[]; onChange: (value: string) => void }) { return <label className="library-select"><span>{label}</span><select value={value} onChange={(event) => onChange(event.target.value)}>{values.map((item)=><option key={item} value={item}>{item}</option>)}</select></label> }
