import { useMemo, useState } from 'react'
import { globalSearchIndex, searchKinds, type SearchResultItem } from '../../data/searchIndex'
import { getCurriculumMatchForSearchItem, getCurriculumOpenLabel } from '../../data/curriculumSearchBridge'
import type { ViewId } from '../../types/knowledge'
import { BadgeList } from '../ui/BadgeList'

interface ModuleSearchCapsulesProps { title: string; eyebrow: string; description: string; areaHints?: string[]; targetViews?: ViewId[]; keywords?: string[]; focusId?: string | null; onNavigate?: (view: ViewId, focusId?: string | null) => void; onOpenAsset?: (assetId: string) => void }
const allValue = 'All'
export function ModuleSearchCapsules({ title, eyebrow, description, areaHints = [], targetViews = [], keywords = [], focusId, onNavigate, onOpenAsset }: ModuleSearchCapsulesProps) {
  const [query, setQuery] = useState('')
  const [kind, setKind] = useState(allValue)
  const [selectedId, setSelectedId] = useState<string | null>(null)
  const moduleItems = useMemo(() => {
    const areaNeedles = areaHints.map((x) => x.toLowerCase())
    const keywordNeedles = keywords.map((x) => x.toLowerCase())
    return globalSearchIndex.filter((item) => {
      const text = `${item.title} ${item.kind} ${item.area} ${item.category} ${item.summary} ${item.tags.join(' ')}`.toLowerCase()
      return areaNeedles.some((needle) => `${item.area} ${item.category}`.toLowerCase().includes(needle)) || targetViews.includes(item.targetView) || keywordNeedles.some((needle) => text.includes(needle))
    })
  }, [areaHints, keywords, targetViews])
  const visible = useMemo(() => { const q = query.trim().toLowerCase(); return moduleItems.filter((item) => kind === allValue || item.kind === kind).filter((item) => !q || `${item.title} ${item.kind} ${item.area} ${item.category} ${item.summary} ${item.tags.join(' ')}`.toLowerCase().includes(q)).sort((a, b) => (a.id === focusId ? -1 : b.id === focusId ? 1 : a.title.localeCompare(b.title))) }, [focusId, kind, moduleItems, query])
  const selected = visible.find((item) => item.id === selectedId) ?? visible.find((item) => item.id === focusId) ?? visible[0]
  const kindOptions = [allValue, ...searchKinds.filter((candidate) => moduleItems.some((item) => item.kind === candidate))]
  const canOpen = Boolean(onNavigate || onOpenAsset)
  const openResult = (item: SearchResultItem) => { if (item.assetId && onOpenAsset) { onOpenAsset(item.assetId); return }; const match = getCurriculumMatchForSearchItem(item); if (match && onNavigate) { onNavigate(match.moduleView, match.submoduleId); return }; if (onNavigate) onNavigate(item.targetView, item.id) }
  return <section className="manual-panel module-capsule-search"><div className="library-filter-header module-capsule-header"><div><span className="eyebrow">{eyebrow}</span><h2>{title}</h2><p>{description}</p></div><div className="module-capsule-stats"><strong>{visible.length}</strong><span>visible capsules</span><small>{moduleItems.length} total in module</small></div></div><div className="module-capsule-toolbar"><input className="library-search-input" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search this module: topics, formulas, outputs, cases, governance pages..." /><label className="library-select"><span>Capsule type</span><select value={kind} onChange={(event) => setKind(event.target.value)}>{kindOptions.map((item) => <option key={item} value={item}>{item}</option>)}</select></label><button className="text-button module-clear-button" onClick={() => { setQuery(''); setKind(allValue); setSelectedId(null) }} type="button">Reset</button></div><div className="module-capsule-layout"><div className="module-capsule-results"><span className="eyebrow">Browse curriculum-aware capsules</span>{visible.length === 0 && <div className="module-capsule-empty"><strong>No capsules found.</strong><p>Clear the filters or search a broader term inside this module.</p></div>}{visible.map((item) => <button className={`search-result-card module-search-card ${selected?.id === item.id ? 'selected' : ''}`} key={`${item.kind}-${item.id}`} onClick={() => setSelectedId(item.id)} type="button"><div><span className="eyebrow">{item.kind}</span><h3>{item.title}</h3><p>{item.summary}</p></div><div className="search-result-meta"><span>{item.area}</span><span>{item.category}</span><span>{getCurriculumOpenLabel(item)}</span></div></button>)}</div>{selected && <ModuleCapsuleDetail item={selected} canOpen={canOpen} onOpen={() => openResult(selected)} />}</div></section>
}
function ModuleCapsuleDetail({ item, canOpen, onOpen }: { item: SearchResultItem; canOpen: boolean; onOpen: () => void }) { const curriculumMatch = getCurriculumMatchForSearchItem(item); return <article className="module-capsule-detail"><div className="command-detail-top"><span className="eyebrow">{item.kind}</span><span className="command-status-pill">{item.area}</span></div><h2>{item.title}</h2><p>{item.summary}</p>{curriculumMatch && <section className="lesson-block success-panel"><div className="lesson-block-title"><span>C</span><h3>Curriculum context</h3></div><p>{curriculumMatch.moduleTitle} → {curriculumMatch.submoduleTitle}</p><BadgeList items={[curriculumMatch.openMode, curriculumMatch.moduleView, `Position ${curriculumMatch.learningPosition || 'submodule'}`]} tone="green" /></section>}<section className="lesson-block"><div className="lesson-block-title"><span>1</span><h3>Where this belongs</h3></div><BadgeList items={[item.area, item.category, item.kind, curriculumMatch?.moduleView ?? item.targetView]} tone="blue" /></section><section className="lesson-block"><div className="lesson-block-title"><span>2</span><h3>Search signals</h3></div><BadgeList items={item.tags.slice(0, 18)} tone="purple" /></section><section className="lesson-block insight-block module-route-block"><div className="lesson-block-title"><span>→</span><h3>Next action</h3></div><p>{curriculumMatch ? 'Open this item through the curriculum-aware route.' : 'Open the focused view for this exact capsule, just like Global Search.'}</p>{canOpen ? <button className="primary-button" onClick={onOpen} type="button">{getCurriculumOpenLabel(item)}</button> : <span className="command-status-pill">Route wiring unavailable</span>}</section></article> }