import type { KnowledgeTooltip } from './knowledgeTooltips'

export const sprint16KnowledgeTooltips: Record<string, KnowledgeTooltip> = {
  'accuracy': {
    label: 'Accuracy',
    meaning: 'Accuracy measures the share of total predictions that are correct.',
    goodSignal: 'Good when classes are balanced and the cost of false positives and false negatives is similar.',
    badSignal: 'Misleading when the dataset is imbalanced. A model can have high accuracy and still miss rare but important events.',
    howToImprove: 'Use precision, recall, F1, PR curve and cost-based thresholding. Handle imbalance and evaluate error types.'
  },
  'f1': {
    label: 'F1 Score',
    meaning: 'F1 is the harmonic mean of precision and recall. It balances false positives and false negatives.',
    goodSignal: 'Higher is better when both precision and recall matter.',
    badSignal: 'Low F1 means either many false positives, many false negatives, or both.',
    howToImprove: 'Tune threshold, improve features, handle class imbalance and compare models using PR curve.'
  },
  'log loss': {
    label: 'Log Loss',
    meaning: 'Log Loss measures how well predicted probabilities match actual outcomes. It heavily penalizes confident wrong predictions.',
    goodSignal: 'Lower is better. Good models assign high probability to events that happen and low probability to events that do not.',
    badSignal: 'High Log Loss means probability estimates are poor or overconfident.',
    howToImprove: 'Improve calibration, reduce overfitting, tune regularization and validate probability quality.'
  },
  'brier score': {
    label: 'Brier Score',
    meaning: 'Brier Score measures the mean squared error of predicted probabilities for binary outcomes.',
    goodSignal: 'Lower is better. A low Brier Score indicates better probability accuracy.',
    badSignal: 'High Brier Score means predicted probabilities do not match observed outcomes well.',
    howToImprove: 'Use calibration methods, review score bands, improve features and validate across time.'
  },
  'pd': {
    label: 'PD',
    meaning: 'Probability of Default. It estimates the chance that a borrower defaults within a defined time horizon.',
    goodSignal: 'Good when calibrated: predicted PD bands should match observed default rates.',
    badSignal: 'Bad when PD underestimates real default risk or changes unstably over time.',
    howToImprove: 'Improve default definition, feature engineering, calibration, time validation and portfolio segmentation.'
  },
  'lgd': {
    label: 'LGD',
    meaning: 'Loss Given Default. It estimates the share of exposure lost if default occurs.',
    goodSignal: 'Good when estimated from realistic recovery and collateral behavior.',
    badSignal: 'Bad when recovery assumptions are stale or too optimistic.',
    howToImprove: 'Use updated recovery data, segment by collateral/product, stress downturn scenarios and validate recoveries.'
  },
  'ead': {
    label: 'EAD',
    meaning: 'Exposure at Default. It estimates how much exposure will be outstanding if default happens.',
    goodSignal: 'Good when it captures drawdown behavior and facility type correctly.',
    badSignal: 'Bad when it ignores unused commitments or customer drawdown behavior before default.',
    howToImprove: 'Model utilization patterns, product type, credit conversion factors and pre-default behavior.'
  },
  'expected loss rate': {
    label: 'Expected Loss Rate',
    meaning: 'Expected loss divided by exposure. It expresses credit risk as a percentage of exposure.',
    goodSignal: 'Good when aligned with portfolio risk appetite, pricing and provisioning expectations.',
    badSignal: 'Bad when unexpectedly high, unstable or inconsistent with observed losses.',
    howToImprove: 'Review PD/LGD/EAD components, recalibrate models and segment portfolio risk.'
  },
  'discount rate': {
    label: 'Discount Rate',
    meaning: 'The required return used to convert future cash flows into present value.',
    goodSignal: 'Good when it matches the risk, currency and timing of the cash flows.',
    badSignal: 'Bad when it is too low for risky cash flows or inconsistent with project risk.',
    howToImprove: 'Revisit WACC, CAPM, country risk, leverage, currency and scenario assumptions.'
  },
  'free cash flow': {
    label: 'Free Cash Flow',
    meaning: 'Cash generated by the business after operating needs and investments, available to capital providers.',
    goodSignal: 'Positive and sustainable free cash flow supports valuation and debt capacity.',
    badSignal: 'Negative or volatile free cash flow increases valuation uncertainty and financing risk.',
    howToImprove: 'Improve margins, working capital, capex discipline and revenue quality.'
  },
  'initial investment': {
    label: 'Initial Investment',
    meaning: 'The upfront cash outflow required to start a project or investment.',
    goodSignal: 'Good when justified by future cash flows and payback logic.',
    badSignal: 'Bad when underestimated, delayed or not matched with realistic cash flow forecasts.',
    howToImprove: 'Stress-test capex, include implementation costs and compare scenarios.'
  },
  'terminal value': {
    label: 'Terminal Value',
    meaning: 'The estimated value of cash flows beyond the explicit forecast period in a DCF valuation.',
    goodSignal: 'Good when assumptions are conservative and consistent with long-term growth and returns.',
    badSignal: 'Bad when terminal value dominates valuation due to aggressive growth or low discount rate.',
    howToImprove: 'Stress long-term growth, margins, WACC and exit multiple assumptions.'
  },
  'risk-free rate': {
    label: 'Risk-free Rate',
    meaning: 'The base return expected from an investment with minimal default risk, often proxied by government bonds.',
    goodSignal: 'Good when matched to the currency and maturity of the cash flows.',
    badSignal: 'Bad when using inconsistent country, currency or maturity assumptions.',
    howToImprove: 'Use a risk-free rate aligned with cash flow currency and time horizon.'
  },
  'beta': {
    label: 'Beta',
    meaning: 'Beta measures how sensitive an asset or company is to market movements.',
    goodSignal: 'Good when estimated from relevant peers or stable market data.',
    badSignal: 'Bad when unstable, based on noisy data or mismatched peers.',
    howToImprove: 'Use comparable companies, unlever/relever beta and test sensitivity.'
  },
  'market risk premium': {
    label: 'Market Risk Premium',
    meaning: 'The extra return investors require for investing in the market instead of a risk-free asset.',
    goodSignal: 'Good when sourced consistently and aligned with the market being analyzed.',
    badSignal: 'Bad when outdated or mixed across countries and currencies.',
    howToImprove: 'Use consistent market references and document country/currency assumptions.'
  },
  'cost of equity': {
    label: 'Cost of Equity',
    meaning: 'The return required by equity investors for bearing ownership risk.',
    goodSignal: 'Good when it reflects systematic risk and market assumptions clearly.',
    badSignal: 'Bad when beta, risk-free rate or market premium are inconsistent.',
    howToImprove: 'Review CAPM inputs, peer beta, risk premium and scenario sensitivity.'
  },
  'missing rate': {
    label: 'Missing Rate',
    meaning: 'The percentage of records where a variable is missing.',
    goodSignal: 'Lower is generally better, but business context matters.',
    badSignal: 'High missing rate can create bias, weak features or unusable variables.',
    howToImprove: 'Investigate source systems, impute carefully, create missing indicators or exclude weak variables.'
  },
  'outlier rate': {
    label: 'Outlier Rate',
    meaning: 'The share of observations that are unusually far from the typical range.',
    goodSignal: 'Good when outliers are understood and either valid or treated appropriately.',
    badSignal: 'Bad when outliers come from errors, fraud, data entry issues or unstable processes.',
    howToImprove: 'Validate with business context, cap/winsorize, transform or model segments separately.'
  },
  'class balance': {
    label: 'Class Balance',
    meaning: 'The distribution of target classes in a classification problem.',
    goodSignal: 'Good when the evaluation strategy accounts for the actual class distribution.',
    badSignal: 'Bad when rare positives make accuracy misleading and thresholds unstable.',
    howToImprove: 'Use PR curves, stratified splits, resampling, class weights and cost-sensitive metrics.'
  },
  'correlation': {
    label: 'Correlation',
    meaning: 'A measure of association between two variables.',
    goodSignal: 'Useful when it reveals relationships, redundancy or multicollinearity risk.',
    badSignal: 'Misleading when treated as causality or when non-linear relationships are ignored.',
    howToImprove: 'Use scatterplots, domain logic, non-linear checks and causal caution.'
  },
  'stability': {
    label: 'Stability',
    meaning: 'How consistent a metric, feature or model behavior remains across time, samples or segments.',
    goodSignal: 'Stable values suggest the model or feature may generalize better.',
    badSignal: 'Unstable values may indicate drift, leakage, small samples or changing business behavior.',
    howToImprove: 'Validate over time, segment analysis, monitor drift and simplify fragile features.'
  }
}
